### ISSUE TITLE
EULA, PP, TOS all lead to same external URL

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/growe#2]
EXP: 
user can access TOS ( EULA/PP)

OBS: 
EULA, PP, TOS all lead to same external URL

FRQ: 
100%

REP: 
- open app
- go to settings
- press button for EULA
- press button for TOS
- press button for PP
- see they all open same URL

Reproduced in version 10 (0.2.5)

**Comment by MKassander** [comment]
We were not able to replicate this issue, the buttons lead to their respective pages both in the engine and as a build.

**Comment by marczaku** [comment]
Confirmed: Fixed. @MKassander
