### ISSUE TITLE
Fusion Button Is Inactive at All Times

### ISSUE THREAD

**Issue by marczaku** [forsbergsskola-se/growe#6]
EXP: 
fusion button is available

OBS: 
fusion button is inactive

FRQ: 
100%

REP:
- open item menu
- see fusion button is faded
- press fusion button
- see fusion button does nothing

**Comment by MKassander** [comment]
The fusion button does work, but it requires you to have three seeds of the same kind. When fusion is available there's a noticable difference in color.

**Comment by marczaku** [comment]
Confirmed: Fixed.
